enum ActionTypes {
  FETCH_PENDING_BRANDS = 'main/Admin/FETCH_PENDING_BRANDS',
  FETCH_PENDING_BRANDS_SUCCESS = 'main/Admin/FETCH_PENDING_BRANDS_SUCCESS',
  FETCH_PENDING_BRANDS_FAILED = 'main/Admin/FETCH_PENDING_BRANDS_FAILED',

  APPROVE_BRAND_REQUEST = 'main/Admin/APPROVE_BRAND_REQUEST',
  REJECT_BRAND_REQUEST = 'main/Admin/REJECT_BRAND_REQUEST',
}

export default ActionTypes;
