interface WatchMeta {
  staticid: string;
  watchname: string;
  watchimage: string;
  referencenumber: string;
  watchmodel: string;
  brandid: string;
  movementid: string;
  genderid: string;
  powerreserve: string;
  casediameter: string;
  casematerialid: string;
  waterresistanceatm: string;
  bezelmaterialid: string;
  glassid: string;
  dialcolorid: string;
  braceletmaterialid: string;
  braceletcolorid: string;
  buckleid: string;
  bucklematerialid: string;
  inner_image: string;
  movementname: string;
  braceletcolorname: string;
  dialcolorname: string;
  gendername: string;
  bucklename: string;
  glassname: string;
  brandname: string;
  casematerialname: string;
  braceletmaterialname: string;
  bucketmaterialname: string;
  minprice: string;
  maxprice: string;
  offers: string;
  currency: string;
  count_models: string;
  min_minprice: string;
  max_maxprice: string;
  count_dynamic: string;
  avg_price: string;
}

export default WatchMeta;
